get_filename_component(FILE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/../../" ABSOLUTE)

if(MSVC12)
    if(CMAKE_CL_64)
        include("${FILE_PREFIX_DIR}/x64Win64VS2013/fastcdr/cmake/fastcdrConfig.cmake")
    else()
        include("${FILE_PREFIX_DIR}/i86Win32VS2013/fastcdr/cmake/fastcdrConfig.cmake")
    endif()
elseif(MSVC14)
    if(CMAKE_CL_64)
        include("${FILE_PREFIX_DIR}/x64Win64VS2015/fastcdr/cmake/fastcdrConfig.cmake")
    else()
        include("${FILE_PREFIX_DIR}/i86Win32VS2015/fastcdr/cmake/fastcdrConfig.cmake")
    endif()
else()
    message(FATAL_ERROR "Not supported version of Visual Studio")
endif()
