macro(check_stdcxx)
    # Check C++11
    include(CheckCXXCompilerFlag)
    if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_COMPILER_IS_CLANG)
        check_cxx_compiler_flag(--std=c++11 SUPPORTS_CXX11)
        if(SUPPORTS_CXX11)
            add_compile_options(--std=c++11)
            set(FASTCDR_SUPPORTS_CXX11 1)
            set(FASTCDR_SUPPORTS_CXX01 1)
        else()
            check_cxx_compiler_flag(--std=c++0x SUPPORTS_CXX01)
            if(SUPPORTS_CXX01)
                add_compile_options(--std=c++0x)
                set(FASTCDR_SUPPORTS_CXX01 1)
            endif()
        endif()
    endif()
endmacro()

macro(check_endianness)
    # Test endianness
    include(TestBigEndian)
    test_big_endian(BIG_ENDIAN)
    set(FASTCDR_BIG_ENDIAN ${BIG_ENDIAN})
    set(FASTCDR_LITTLE_ENDIAN !${BIG_ENDIAN})
endmacro()
