macro(check_stdcxx)
    # Check C++11
    include(CheckCXXCompilerFlag)
    if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_COMPILER_IS_CLANG)
        check_cxx_compiler_flag(--std=c++11 SUPPORTS_CXX11)
        if(SUPPORTS_CXX11)
            add_compile_options(--std=c++11)
            set(HAVE_CXX11 1)
        endif()
    else()
        set(HAVE_CXX11 1)
    endif()
endmacro()

macro(check_endianness)
    # Test endianness
    include(TestBigEndian)
    test_big_endian(BIG_ENDIAN)
    set(__BIG_ENDIAN__ ${BIG_ENDIAN})
endmacro()

macro(check_msvc_arch)
    if("${CMAKE_GENERATOR}" STREQUAL "Visual Studio 10 2010")
        set(MSVC_ARCH "i86Win32VS2010")
    elseif("${CMAKE_GENERATOR}" STREQUAL "Visual Studio 10 2010 Win64")
        set(MSVC_ARCH "x64Win64VS2010")
    elseif("${CMAKE_GENERATOR}" STREQUAL "Visual Studio 11 2012")
        set(MSVC_ARCH "i86Win32VS2012")
    elseif("${CMAKE_GENERATOR}" STREQUAL "Visual Studio 11 2012 Win64")
        set(MSVC_ARCH "x64Win64VS2012")
    elseif("${CMAKE_GENERATOR}" STREQUAL "Visual Studio 12 2013")
        set(MSVC_ARCH "i86Win32VS2013")
    elseif("${CMAKE_GENERATOR}" STREQUAL "Visual Studio 12 2013 Win64")
        set(MSVC_ARCH "x64Win64VS2013")
    else()
        set(MSVC_ARCH "unknown")
    endif()
endmacro()
