# .github/workflows/mirror.yml
on:
  push:
    branches:
      - 'master'
      - '1.1.x'
jobs:
  mirror_job_master:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    name: Mirror master branch to API & ABI compatible minor version branches
    strategy:
      fail-fast: false
      matrix:
        dest_branch:
          - '2.3.x'
          - '2.x'
    steps:
    - name: Mirror action step
      id: mirror
      uses: eProsima/eProsima-CI/external/mirror-branch-action@v0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        source: 'master'
        dest: ${{ matrix.dest_branch }}
  mirror_job_1_x:
    if: github.ref == 'refs/heads/1.1.x'
    runs-on: ubuntu-latest
    name: Mirror 1.1.x branch to API & ABI compatible minor version branches
    strategy:
      fail-fast: false
      matrix:
        dest_branch:
          - '1.x'
    steps:
    - name: Mirror action step
      id: mirror
      uses: eProsima/eProsima-CI/external/mirror-branch-action@v0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        source: '1.1.x'
        dest: ${{ matrix.dest_branch }}
